#!/usr/bin/env python3
"""NewsBrewer Configuration UI — run with: python config_ui.py"""

import os
import sys
import json
import webbrowser
from pathlib import Path
from threading import Timer

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from flask import Flask, render_template, request, jsonify, redirect, url_for
import yaml
from dotenv import dotenv_values

app = Flask(__name__, template_folder="templates")
ROOT = Path(__file__).parent
CONFIG_FILE = ROOT / "config.yml"
ENV_FILE = ROOT / ".env"

def load_current_config() -> dict:
    """Load current values from config.yml and .env into a flat dict for the form."""
    config = {}

    # Load .env
    env_vals = dotenv_values(ENV_FILE) if ENV_FILE.exists() else {}
    config["account_1_email"] = env_vals.get("ACCOUNT_1_EMAIL", "")
    config["account_1_password"] = env_vals.get("ACCOUNT_1_PASSWORD", "")
    config["account_2_email"] = env_vals.get("ACCOUNT_2_EMAIL", "")
    config["account_2_password"] = env_vals.get("ACCOUNT_2_PASSWORD", "")
    config["smtp_email"] = env_vals.get("SMTP_EMAIL", "")
    config["smtp_password"] = env_vals.get("SMTP_PASSWORD", "")
    config["digest_recipient"] = env_vals.get("DIGEST_RECIPIENT", "")
    config["github_token"] = env_vals.get("GITHUB_TOKEN", "")
    config["github_repo"] = env_vals.get("GITHUB_REPO", "")

    # Load config.yml
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            yml = yaml.safe_load(f) or {}

        ai = yml.get("ai_focus", {})
        config["language"] = ai.get("language", "nl")
        config["interesting_topics"] = "\n".join(ai.get("interesting_topics", []))
        config["not_interesting_topics"] = "\n".join(ai.get("not_interesting_topics", []))
        config["min_relevance_score"] = ai.get("min_relevance_score", 6.0)

        delivery = yml.get("delivery", {})
        config["smtp_server"] = delivery.get("smtp_server", "smtp.gmail.com")
        config["smtp_port"] = delivery.get("smtp_port", 587)
        config["max_articles"] = delivery.get("max_articles", 10)
        config["schedule"] = delivery.get("schedule", "0 6 * * *")
        config["timezone"] = delivery.get("timezone", "Europe/Brussels")

        model = yml.get("model", {})
        config["model_name"] = model.get("name", "gpt-4o-mini")
        config["manual_keyword"] = yml.get("email_sources", {}).get("manual_keyword", "BREW")

    return config


@app.route("/")
def index():
    config = load_current_config()
    return render_template("config_ui.html", config=config)


@app.route("/save", methods=["POST"])
def save():
    """Save form data to config.yml and .env"""
    form = request.form

    # Write .env
    env_content = f"""# NewsBrewer credentials — auto-generated by Config UI

ACCOUNT_1_EMAIL={form.get('account_1_email', '')}
ACCOUNT_1_PASSWORD={form.get('account_1_password', '')}
ACCOUNT_2_EMAIL={form.get('account_2_email', '')}
ACCOUNT_2_PASSWORD={form.get('account_2_password', '')}
SMTP_EMAIL={form.get('smtp_email', '')}
SMTP_PASSWORD={form.get('smtp_password', '')}
DIGEST_RECIPIENT={form.get('digest_recipient', '')}
GITHUB_TOKEN={form.get('github_token', '')}
GITHUB_REPO={form.get('github_repo', '')}
"""
    ENV_FILE.write_text(env_content)

    # Write config.yml
    interesting = [l.strip() for l in form.get('interesting_topics', '').splitlines() if l.strip()]
    not_interesting = [l.strip() for l in form.get('not_interesting_topics', '').splitlines() if l.strip()]

    # Read existing config to preserve email accounts structure
    existing = {}
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            existing = yaml.safe_load(f) or {}

    config = {
        "email_sources": {
            "accounts": existing.get("email_sources", {}).get("accounts", []),
            "newsletter_senders": [],
            "manual_keyword": form.get("manual_keyword", "BREW"),
        },
        "ai_focus": {
            "language": form.get("language", "nl"),
            "interesting_topics": interesting,
            "not_interesting_topics": not_interesting,
            "min_relevance_score": float(form.get("min_relevance_score", 6.0)),
            "highlight_courses": True,
        },
        "delivery": {
            "smtp_server": form.get("smtp_server", "smtp.gmail.com"),
            "smtp_port": int(form.get("smtp_port", 587)),
            "smtp_email": "",
            "smtp_password": "",
            "send_to": "",
            "max_articles": int(form.get("max_articles", 10)),
            "schedule": form.get("schedule", "0 6 * * *"),
            "timezone": form.get("timezone", "Europe/Brussels"),
            "github_repo": form.get("github_repo", ""),
        },
        "model": {
            "provider": "github_models",
            "name": form.get("model_name", "gpt-4o-mini"),
        },
    }

    with open(CONFIG_FILE, "w") as f:
        yaml.dump(config, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

    return redirect(url_for("index") + "?saved=1")


@app.route("/test-imap", methods=["POST"])
def test_imap():
    """Test IMAP connection and return JSON result."""
    data = request.json
    try:
        from src.utils.imap_helper import connect, disconnect

        server = data.get("server", "imap.gmail.com")

        mail = connect(server=server, port=993, email=data["email"], password=data["password"])
        if mail:
            disconnect(mail)
            return jsonify({"ok": True, "message": f"Verbinding geslaagd met {server}"})
        else:
            return jsonify({"ok": False, "message": "Verbinding mislukt — controleer je email en app-wachtwoord"})
    except Exception as e:
        return jsonify({"ok": False, "message": f"Fout: {str(e)}"})


@app.route("/send-test", methods=["POST"])
def send_test():
    """Send a test digest email."""
    try:
        from datetime import date
        from src.models.digest_item import DigestItem
        from src.utils.config_loader import load_config
        from src.agents.digest_agent import DigestAgent

        config = load_config()
        items = [
            DigestItem(
                url="https://anthropic.com/news/claude",
                title="Test artikel — NewsBrewer werkt correct",
                source="anthropic.com",
                summary="Dit is een testmail van NewsBrewer om te bevestigen dat de configuratie correct is en emails succesvol verstuurd worden.",
                is_course=False,
                relevance_score=9.0,
                tags=["test", "NewsBrewer"],
                date=date.today(),
            )
        ]
        DigestAgent(config).run(items)
        return jsonify({"ok": True, "message": f"Testmail verstuurd naar {config.delivery.send_to}"})
    except Exception as e:
        return jsonify({"ok": False, "message": f"Fout: {str(e)}"})


def open_browser():
    webbrowser.open("http://localhost:5000")


if __name__ == "__main__":
    print("NewsBrewer Config UI — http://localhost:5000")
    Timer(1.0, open_browser).start()
    app.run(debug=False, port=5000)
